definitions:
  services:
    mysql:
      image: 'mysql:5.7'
      variables:
        MYSQL_DATABASE: wordpress
        MYSQL_ROOT_PASSWORD: secret
pipelines:
  default:
    - step:
        image: 'php:7-apache'
        services:
          - mysql
          - docker
        script:
          - apt -qq update && apt install -y unzip zlib1g-dev default-mysql-client wget subversion git libonig-dev
          - docker-php-ext-install mysqli 
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp
          - chown -R www-data:www-data /var/www 
          - runuser -s /bin/bash -c "wp core download --path=/var/www/html" www-data
          - runuser -s /bin/bash -c "wp config create --dbname=wordpress --dbuser=root --dbpass=secret --dbhost=127.0.0.1 --force --skip-check --path=/var/www/html" www-data
          - runuser -s /bin/bash -c "wp core install --url=example.com --title=Example --admin_user=admin --admin_password=secret --admin_email=test@example.com --path=/var/www/html" www-data
          - ln -s $BITBUCKET_CLONE_DIR /var/www/html/wp-content/plugins/vegashero
          - runuser -s /bin/bash -c "/var/www/html/wp-content/plugins/vegashero/bin/install-wp-tests.sh wordpress root secret 127.0.0.1 latest true" www-data
          - runuser -s /bin/bash -c "/usr/local/bin/composer install -n --prefer-dist --working-dir=/var/www/html/wp-content/plugins/vegashero/" www-data
          - runuser -s /bin/bash -c "/usr/local/bin/composer test --working-dir=/var/www/html/wp-content/plugins/vegashero/" www-data

