version: "2.2"
services:

    php-apache:
        extends: 
            file: common.yml
            service: wordpress
        build: 
            context: .
            dockerfile: Dockerfile
        #cpuset: "0"
        #cpu_quota: 10000
        #mem_limit: 128m
        links:
            - mariadb
        volumes:
          - .:/var/www/html/wp-content/plugins/vegashero

    tests:
        extends: 
            file: common.yml
            service: wordpress
        build: 
            context: .
            dockerfile: Dockerfile.test
        #cpuset: "0"
        #cpu_quota: 10000
        #mem_limit: 128m
        links:
            - mariadb
        volumes:
          - .:/var/www/html/wp-content/plugins/vegashero

    mariadb:
        #cpuset: "0"
        #cpu_quota: 10000
        #mem_limit: 128m
        image: mariadb:10.3
        environment:
            - MYSQL_DATABASE=wordpress
            - MYSQL_USER=wordpress
            - MYSQL_PASSWORD=secret
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes



