version: "3.7"

services:

    wordpress:
      build: 
        context: ./dockerfiles
        dockerfile: plugin
        args: 
          - USER_ID
          - DB_NAME=wordpress
          - DB_USER=wordpress
          - DB_PASSWORD=secret
          - DB_HOST=db
      ports:
          - "8080:80"
      environment:
          - VEGASHERO_ENV
          - DB_NAME=wordpress
          - DB_USER=wordpress
          - DB_PASSWORD=secret
          - DB_HOST=db
      #cpuset: "0"
      #cpu_quota: 10000
      #mem_limit: 128m
      depends_on:
        - db
      volumes:
        - .:/var/www/html/wp-content/plugins/vegashero
      networks:
        default:
          aliases:
            - vegashero.example.com

    tests:
      build: 
        context: ./dockerfiles
        dockerfile: test
        args: 
          - USER_ID
          - DB_NAME=wordpress
          - DB_USER=wordpress
          - DB_PASSWORD=secret
          - DB_HOST=db
      #cpuset: "0"
      #cpu_quota: 10000
      #mem_limit: 128m
      depends_on:
        - db
      volumes:
        - .:/var/www/html/wp-content/plugins/vegashero
      ports:
        - "8080:80"
      environment:
        - VEGASHERO_ENV
        - DB_NAME=wordpress
        - DB_USER=wordpress
        - DB_PASSWORD=secret
        - DB_HOST=db

    db:
      image: mariadb:10.3
      environment:
        - MYSQL_DATABASE=wordpress
        - MYSQL_USER=wordpress
        - MYSQL_PASSWORD=secret
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      volumes:
        - /var/lib/mysql
      #cpuset: "0"
      #cpu_quota: 10000
      #mem_limit: 128m
