version: "2"
services:

    wordpress:
        build: .
        ports:
            - "8080:80"
        links:
            - mysql
        environment:
            - TERM=xterm
            - DB_NAME=wordpress
            - DB_USER=wordpress
            - DB_PASSWORD=secret
            - DB_HOST=mysql
            - AUTH_KEY=''
            - SECURE_AUTH_KEY=''
            - LOGGED_IN_KEY=''
            - NONCE_KEY=''
            - AUTH_SALT=''
            - SECURE_AUTH_SALT=''
            - LOGGED_IN_SALT=''
            - NONCE_SALT=''
            - WP_DEBUG=true

    mysql:
        image: mysql:5.5
        environment:
            - MYSQL_DATABASE=wordpress
            - MYSQL_USER=wordpress
            - MYSQL_PASSWORD=secret
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes


