version: "2"
services:

    dev:
        extends: 
            file: common.yml
            service: wordpress
        links:
            - mysql
    tests:
        extends: 
            file: common.yml
            service: wordpress
        build: 
            context: .
            dockerfile: Dockerfile.test
        links:
            - mysql

    mysql:
        image: mysql:5.5
        environment:
            - MYSQL_DATABASE=wordpress
            - MYSQL_USER=wordpress
            - MYSQL_PASSWORD=secret
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes


