version: "3.6"

services:

    php-apache:
        build: 
            context: .
            args: 
                - USER_NAME
                - USER_ID
                - DB_NAME=wordpress
                - DB_USER=wordpress
                - DB_PASSWORD=secret
                - DB_HOST=mariadb
        ports:
            - "8080:80"
        environment:
            - VEGASHERO_ENV
            - TERM=xterm
            - COLUMNS=141
            - LINES=41
            - DB_NAME=wordpress
            - DB_USER=wordpress
            - DB_PASSWORD=secret
            - DB_HOST=mariadb
            - AUTH_KEY=''
            - SECURE_AUTH_KEY=''
            - LOGGED_IN_KEY=''
            - NONCE_KEY=''
            - AUTH_SALT=''
            - SECURE_AUTH_SALT=''
            - LOGGED_IN_SALT=''
            - NONCE_SALT=''
            - WP_DEBUG=true
            - FS_METHOD=direct

    tests:
        build: 
            context: .
            args: 
                - USER_NAME
                - USER_ID
                - DB_NAME=wordpress
                - DB_USER=wordpress
                - DB_PASSWORD=secret
                - DB_HOST=mariadb
        ports:
            - "8080:80"
        environment:
            - VEGASHERO_ENV
            - TERM=xterm
            - COLUMNS=141
            - LINES=41
            - DB_NAME=wordpress
            - DB_USER=wordpress
            - DB_PASSWORD=secret
            - DB_HOST=mariadb
            - AUTH_KEY=''
            - SECURE_AUTH_KEY=''
            - LOGGED_IN_KEY=''
            - NONCE_KEY=''
            - AUTH_SALT=''
            - SECURE_AUTH_SALT=''
            - LOGGED_IN_SALT=''
            - NONCE_SALT=''
            - WP_DEBUG=true
            - FS_METHOD=direct
