services:

    web:
      build: 
        context: .
        args: 
          - USER_ID=1000
          - DB_NAME=wordpress
          - DB_USER=wordpress
          - DB_PASSWORD=secret
          - DB_HOST=db
      #cpuset: "0"
      #cpu_quota: 10000
      #mem_limit: 128m
      depends_on:
        - db
      volumes:
        - .:/usr/local/src
      ports:
        - "4360:80"
      environment:
        - VEGASHERO_ENV
        - DB_NAME=wordpress
        - DB_USER=wordpress
        - DB_PASSWORD=secret
        - DB_HOST=db

    db:
      image: mariadb:10.3
      environment:
        - MYSQL_DATABASE=wordpress
        - MYSQL_USER=wordpress
        - MYSQL_PASSWORD=secret
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      volumes:
        - /var/lib/mysql
      #cpuset: "0"
      #cpu_quota: 10000
      #mem_limit: 128m
