version: "2"
services:

    php-apache:
        extends: 
            file: common.yml
            service: wordpress
        build: 
            context: .
            dockerfile: Dockerfile
        #cpuset: "0"
        #cpu_quota: 10000
        #mem_limit: 128m
        links:
            - mysql

    php5.6-lsphp:
        extends: 
            file: common.yml
            service: wordpress
        build: 
            context: .
            dockerfile: Dockerfile.lsphp
        ports:
          - "8088:8088"
          - "7080:7080"
        links:
            - mysql

    tests:
        extends: 
            file: common.yml
            service: wordpress
        build: 
            context: .
            dockerfile: Dockerfile.test
        #cpuset: "0"
        #cpu_quota: 10000
        #mem_limit: 128m
        links:
            - mysql

    mysql:
        #cpuset: "0"
        #cpu_quota: 10000
        #mem_limit: 128m
        image: mysql:5.5
        environment:
            - MYSQL_DATABASE=wordpress
            - MYSQL_USER=wordpress
            - MYSQL_PASSWORD=secret
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes



