CREATE DATABASE IF NOT EXISTS vegasdb DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS vegasdb.sites ( 
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
    name VARCHAR(255) NOT NULL , `type` ENUM('iframe', 'embed') NOT NULL , 
    created TIMESTAMP NULL DEFAULT NULL , 
    modified TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ) 
    ENGINE = InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS vegasdb.games (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    site_id INT NOT NULL ,
    name VARCHAR(255) NOT NULL,
    provider VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL,
    ref VARCHAR(128) NOT NULL COMMENT 'provided game identifier',
    status BOOLEAN NOT NULL DEFAULT 1,
    large_image VARCHAR(300),
    thumb_image VARCHAR(300),
    created TIMESTAMP NULL DEFAULT NULL,
    modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDb DEFAULT CHARSET=utf8;

CREATE INDEX games_site_ids ON vegasdb.games (site_id);



