# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers # ...with this image as the primary container; this is where all `steps` will run
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: tkuchiki/delayed-mysql
        environment: 
          MYSQL_DATABASE: wordpress
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: secret
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          #MYSQL_DATABASE: wordpress
          #MYSQL_ROOT_PASSWORD: ''
          #MYSQL_ALLOW_EMPTY_PASSWORD: yes
          
    working_directory: ~/laravel # directory where steps will run

    working_directory: ~/vegashero

    steps:
      - run: 
          name: Install MySQL Client
          command: |
            apt -qq update && apt install -y unzip zlib1g-dev mysql-client wget subversion git
            docker-php-ext-install mysqli mbstring pcntl zip
      - run: 
          name: Install WP CLI
          command: | 
            curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp
      - run:
          name: Install Wordpress
          command: |
            wp core download  --allow-root
            wp config create --dbname=wordpress --dbuser=root --dbhost=127.0.0.1:3306 --force --skip-check --allow-root
            wp core install --url=example.com --title=Example --admin_user=admin --admin_password=secret --admin_email=test@example.com --allow-root

      - run:
          name: Scaffold Wordpress Plugin Tests
          command: |
            wp scaffold plugin-tests vegashero  --allow-root

      - run:
          name: Install Wordpress Plugin Tests
          command: |
            $CIRCLE_WORKING_DIRECTORY/wp-content/plugins/vegashero/bin/install-wp-tests.sh wordpress root 

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - run: phpunit $CIRCLE_WORKING_DIRECTORY/wp-content/plugins/vegashero

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
