# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      #- image: circleci/php:7.1-node-browsers # ...with this image as the primary container; this is where all `steps` will run
      - image: circleci/php:7.1-apache
      - image: mysql:5.5
        environment: 
          #MYSQL_DATABASE: wordpress
          #MYSQL_USER: wordpress
          #MYSQL_PASSWORD: secret
          #MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: wordpress
          MYSQL_ROOT_PASSWORD: secret

    steps:
      - run:
          name: Chown
          command: |
            sudo chgrp -R circleci /usr/local/bin
      - run: 
          name: Install MySQL Client
          command: |
            sudo apt -qq update && sudo apt install -y unzip zlib1g-dev default-mysql-client wget subversion git 
            sudo docker-php-ext-install mysqli mbstring pcntl zip
      - run:
          name: Install Composer
          command: |
            curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - run: 
          name: Install WP CLI
          command: | 
            curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp
      - run:
          name: Install Wordpress
          command: |
            wp core download --path=/home/circleci/project/
            wp config create --dbname=wordpress --dbuser=root --dbpass=secret --dbhost=127.0.0.1 --force --skip-check --path=/home/circleci/project/
            wp core install --url=example.com --title=Example --admin_user=admin --admin_password=secret --admin_email=test@example.com --path=/home/circleci/project/

      - checkout:
          path: /home/circleci/project/wp-content/plugins/vegashero/

      - run:
          name: Install Wordpress Plugin Tests
          command: |
            /home/circleci/project/wp-content/plugins/vegashero/bin/install-wp-tests.sh wordpress root secret 127.0.0.1 latest true

      - run: 
          name: Install composer packages
          command: |
            composer install -n --prefer-dist --working-dir=/home/circleci/project/wp-content/plugins/vegashero/
      - run:
          name: WP Config
          command: |
            ls -l /home/circleci/project
            cat /home/circleci/project/wp-config.php

      - run:
          name: Symlink
          command: |
            ln -s /home/circleci/project/wp-content/plugins/vegashero /tmp/wordpress/wp-content/plugins/vegashero

      - run: composer test --working-dir=/home/circleci/project/wp-content/plugins/vegashero/
