# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      #- image: circleci/php:7.1-node-browsers # ...with this image as the primary container; this is where all `steps` will run
      - image: php:7.1-apache
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: mysql:5.5
        environment: 
          MYSQL_DATABASE: wordpress
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: secret
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          #MYSQL_DATABASE: wordpress
          #MYSQL_ROOT_PASSWORD: ''
          #MYSQL_ALLOW_EMPTY_PASSWORD: yes
          
    steps:
      - run: 
          name: Install MySQL Client
          command: |
            apt -qq update && apt install -y unzip zlib1g-dev mysql-client wget subversion git
            docker-php-ext-install mysqli mbstring pcntl zip
      - run:
          name: Install Composer
          command: |
            curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - run: 
          name: Install WP CLI
          command: | 
            curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp
      - run:
          name: Install Wordpress
          command: |
            wp core download  --path=/root/project/ --allow-root
            wp config create --dbname=wordpress --dbuser=root --dbhost=127.0.0.1:3306 --force --skip-check --allow-root
            wp core install --url=example.com --title=Example --admin_user=admin --admin_password=secret --admin_email=test@example.com --allow-root

      - checkout:
          path: /root/project/wp-content/plugins/vegashero

      - run:
          name: Install Wordpress Plugin Tests
          command: |
            /root/project/wp-content/plugins/vegashero/bin/install-wp-tests.sh wordpress wordpress secret localhost latest true

      - run: composer install -n --prefer-dist --working-dir=/root/project/wp-content/plugins/vegashero

      - run: composer test --working-dir=/root/project/wp-content/plugins/vegashero

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
